### ISSUE TITLE
Enhancement: jstrdecode should have a command line option to ignore newlines

### ISSUE THREAD

**Issue by lcn2** [xexyl/jparse#21]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the enhancement

When `jstedecode(1)` processes data from stdin, it should have a command line option to ignore newlines.

Consider:

```sh
echo 'å∫ç∂' | jstrdecode
```

This will generate the following unhelpful error:

```
Warning: json_decode: found non-\-escaped char: 0x0a
Warning: jstrdecode_stream: error while decoding stdin buffer
Warning: main: failed to decode string from stdin
```

Whereas this works:

```sh
echo -n 'å∫ç∂' | jstrdecode
```

and produces:

```
å∫ç∂
```

The same problem happens when you use the `-` (dash character) arg:

```sh
echo 'å∫ç∂' | jstrdecode -
```

**IMPORTANT NOTE**: Objecting to a "naked" newline in a JSON string **IS CORRECT BEHAVIOR** as the so-called JSON spec does **NOT** allow for "naked" newlines in JSON strings.

### Relevant images, screenshots or other files

`echo Hello, World! | jstrdecode`  :-)

### Relevant links

🔗⛓️

### Anything else?

This is **NOT** a priority.  The bin tools on that "other" repo supply a `-T` to trim outgoing newlines before feeding them into `jstrdecode -`.  So there is no need for an emergency fix.  We held off on making this change until after the code freeze.

"Technically and pedantically speaking" (as the expression goes), the current behavior of `jstrdecode(1)` is correct.  The tool does "decode JSON encoded strings" and in the so-called JSON spec, newlines characters are **NOT** allowed.  The JSON parser `jparse(1)` and its friendly library should **NOT** be relaxed to allow for naked newline characters in JSON documents.

Perhaps `jstrdecode(1)` should `jstrdecode(1)` have an option to ignore any final newline?

We observe that its companion `jstrencode(1)` tool has `-n`:

```
	-n		do not output newline after encode output (def: print final newline)
```

As does `jstrdecode(1)`:

```
	-n		do not output newline after decode output
```

Perhaps a new option such as `-N` should tell `jstrdecode` to ignore a final newline, such that this would work:

```sh
echo 'å∫ç∂' | jstrdecode -N
```

Note that internal newlines would still cause this to fail:

```sh
echo -n 'å∫ç∂
´ƒ©˙' | jstrdecode -N
```

This is **NOT** a priory enhancement request.

**Comment by xexyl** [comment]
I like this thought. 

If I understand it correctly this would skip past the byte `0x0a` when decoding, if it's the final byte? If so that is a good idea and would help with typing the commands. I don't think it would break JSON validity either since it's only for inputting commands, not JSON itself.

**Comment by lcn2** [comment]
With `-N` one might consider that when reading internal newlines from stdin, that they each be treated as a separate argument so that:

```sh
echo -n 'å∫ç∂' 'ƒ©˙' | jstrdecode
```

and:

```sh
echo 'å∫ç∂
ƒ©˙' | jstrdecode -N
```

would produce the same thing?

## UPDATE 0

See also [GH-issuecomment-2405771581](https://github.com/ioccc-src/mkiocccentry/pull/1001#issuecomment-2405771581) ᐤ.

**Comment by xexyl** [comment]
> With `-N` one might consider that when reading internal newlines from stdin, that they each be treated as a separate argument so that:
> 
> ```shell
> echo -n 'å∫ç∂' 'ƒ©˙' | jstrdecode
> ```
> 
> and:
> 
> ```shell
> echo 'å∫ç∂
> ƒ©˙' | jstrdecode -N
> ```
> 
> would produce the same thing?

I wonder. I was just doing it so it would skip the final newline which seems reasonable. But the question is if one uses it this way what does a final newline do? Meaning a trailing newline?

> 
> ## UPDATE 0
> See also [GH-issuecomment-2405771581](https://github.com/ioccc-src/mkiocccentry/pull/1001#issuecomment-2405771581) ᐤ.

I replied with a question on that.

**Comment by xexyl** [comment]
I just implemented the way I interpreted it. I can commit. If you wish for more then let me know. I have to check one thing. After this I then must do other things. (Okay did it in decode only: have to look at encode also.)

**Comment by lcn2** [comment]
Regarding [GH-issuecomment-2405774413](https://github.com/xexyl/jparse/issues/21#issuecomment-2405774413), see the suggestion for[ processing internal newlines](https://github.com/xexyl/jparse/issues/21#issuecomment-2405780991) with `-N` as well.

The `-N` option would be limited to the internals of `jstrdecode(1)` only, and would not impact the JSON parser code.

We suggest that with `-N`, that  `jstrdecode(1)` buffer stdin into memory, scan it removing newlines, before passing it on to the JSON string decoder.

**Comment by lcn2** [comment]
> I just implemented the way I interpreted it. I can commit. If you wish for more then let me know. I have to check one thing. After this I then must do other things. (Okay did it in decode only: have to look at encode also.)

Please do commit, and feel free to add it to the "other repo".

**Comment by xexyl** [comment]
> > I just implemented the way I interpreted it. I can commit. If you wish for more then let me know. I have to check one thing. After this I then must do other things. (Okay did it in decode only: have to look at encode also.)
> 
> Please do commit, and feel free to add it to the "other repo".

I'll do that and the other part can happen later I guess as I have another question about that way.

**Comment by lcn2** [comment]
> > Regarding [GH-issuecomment-2405774413](https://github.com/xexyl/jparse/issues/21#issuecomment-2405774413), see the suggestion for[ processing internal newlines](https://github.com/xexyl/jparse/issues/21#issuecomment-2405780991) with `-N` as well.
> > The `-N` option would be limited to the internals of `jstrdecode(1)` only, and would not impact the JSON parser code.
> > We suggest that with `-N`, that `jstrdecode(1)` buffer stdin into memory, scan it removing newlines, before passing it on to the JSON string decoder.
> 
> Okay assuming I remove internal `\n`. What would it do? How would it be removed? If I changed to a NUL byte that could be a problem. Changing it to space might be wrong too.
> 
> I guess if it's the final byte it would be like I am doing now?

We suggest you delete it from the buffer.

The command:

```sh
jstrdecode 'foo' 'bar'
```

concatenates both "foo" and "bar".

So think of:

```sh
(echo "foo"; echo "bar") | jstrdecode -N
```

as removing both newlines.

**Comment by xexyl** [comment]
About to do a pull request. If you wish to explain your further idea with `-N` please do so.

**Comment by lcn2** [comment]
> About to do a pull request. If you wish to explain your further idea with `-N` please do so.

With `-N`, the `jstrdecode` command would ignore all newlines found.

```sh
	-N		ignore all newlines (def: treat them as JSON string errors
```

**Comment by lcn2** [comment]
> Okay I understand now. Not sure I can do this today but the final newline is at least removed now.
> 
> Perhaps you would like to do this quickly before the freeze over there? That would be appreciated if you have the time. Otherwise I can do it tomorrow I guess (or later today if I have time - but I doubt it).

We have a tested PR that we will issue to the jparse repo.  Then we will fold that PR into this repo after we complete the existing PR processing to be sure we stay in sync.

**Comment by xexyl** [comment]
If you think your updates resolves this issue then please feel free to close this, or let me know and I'll close it. If not then please let me know what else you think needs to be done.

**Comment by lcn2** [comment]
I see that you added `-N` to jstrencode.   OK.   Well it seems that a similar PR will have to be added for that command as well.   Stay tuned.

**Comment by xexyl** [comment]
> I see that you added `-N` to jstrencode. OK. Well it seems that a similar PR will have to be added for that command as well. Stay tuned.

Sure. Please make sure to update the man page too. You can then sync to mkiocccentry when you're all done. I should be able to merge it today but if I don't get to it today I'll certainly do it in the morning (when I'm awake enough to look at it).

I guess that won't matter for a code freeze over in the mkiocccentry repo. Even so I'll be awake for many more hours just not as many as you.

**Comment by lcn2** [comment]
> > I see that you added `-N` to jstrencode. OK. Well it seems that a similar PR will have to be added for that command as well. Stay tuned.
> 
> Sure. Please make sure to update the man page too. You can then sync to mkiocccentry when you're all done. I should be able to merge it today but if I don't get to it today I'll certainly do it in the morning (when I'm awake enough to look at it).
> 
> I guess that won't matter for a code freeze over in the mkiocccentry repo. Even so I'll be awake for many more hours just not as many as you.

PR is own the way soon, after man page edits.

**Comment by xexyl** [comment]
> > > I see that you added `-N` to jstrencode. OK. Well it seems that a similar PR will have to be added for that command as well. Stay tuned.
> > 
> > 
> > Sure. Please make sure to update the man page too. You can then sync to mkiocccentry when you're all done. I should be able to merge it today but if I don't get to it today I'll certainly do it in the morning (when I'm awake enough to look at it).
> > I guess that won't matter for a code freeze over in the mkiocccentry repo. Even so I'll be awake for many more hours just not as many as you.
> 
> PR is own the way soon, after man page edits.

Sounds good. Thanks!

**Comment by xexyl** [comment]
Feel free to do the update you were thinking of with `-t` too. That'd be great as I'm not sure what code point you're referring to and it would also be fun to see what you have in mind.

**Comment by lcn2** [comment]
Double free bug .. need to fix.

**Comment by xexyl** [comment]
> Double free bug .. need to fix.

Forgot to set to NULL? Or did I do something when I did the original addition very quickly ? Well anyway no problem. I will be going afk shortly but I'll have my phone with me.

**Comment by lcn2** [comment]
> > Double free bug .. need to fix.
> 
> Forgot to set to NULL? Or did I do something when I did the original addition very quickly ? Well anyway no problem. I will be going afk shortly but I'll have my phone with me.

The `jstrencode_stream()` function is sometimes called with a non-malloced data.

**Comment by lcn2** [comment]
The `jstrencode_stream()` function needs fixing ...

**Comment by xexyl** [comment]
> The `jstrencode_stream()` function needs fixing ...

I hope you're a strong swimmer!

**Comment by lcn2** [comment]
> > The `jstrencode_stream()` function needs fixing ...
> 
> I hope you're a strong swimmer!

Fixed.

**Comment by lcn2** [comment]
Doing the man page change now.

**Comment by xexyl** [comment]
> > > The `jstrencode_stream()` function needs fixing ...
> > 
> > 
> > I hope you're a strong swimmer!
> 
> Fixed.

Great.

**Comment by xexyl** [comment]
> Doing the man page change now.

Thanks!

**Comment by lcn2** [comment]
Done.  Just a bit of hand testing now ...

**Comment by lcn2** [comment]
building the commit ...

**Comment by xexyl** [comment]
Sounds good.

**Comment by lcn2** [comment]
creating the PR ...

Watching the GitHub test ...

```
debug[3]: \ud83d\ude4f\uD83D\uDD25\uD83D\uDC09: 🙏🔥🐉 == 🙏🔥🐉: true
debug[3]: \uD83D\uDC8D\uD83C\uDF0B: 💍🌋 == 💍🌋: true
```

🤓

**Comment by lcn2** [comment]
See PR #23

**Comment by lcn2** [comment]
We believe this issue has been completed.

**Comment by xexyl** [comment]
> creating the PR ...
> 
> 
> 
> Watching the GitHub test ...
> 
> 
> 
> ```
> 
> debug[3]: \ud83d\ude4f\uD83D\uDD25\uD83D\uDC09: 🙏🔥🐉 == 🙏🔥🐉: true
> 
> debug[3]: \uD83D\uDC8D\uD83C\uDF0B: 💍🌋 == 💍🌋: true
> 
> ```
> 
> 
> 
> 🤓

Maybe I should have done the other one as well but the joke of course is that you have this person praying and yet a dragon is consuming them in fire!
